import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import type { Run } from '@/backend/types';
import { money, formatFullDateTime } from './format';

function buildHtml(run: Run): string {
  const machineIds = Object.keys(run.machines);

  const lastRows = machineIds
    .map((id) => {
      const m = run.machines[id];
      return `<tr><td>${m.label}</td><td>${money(m.lastIn)}</td><td>${money(m.lastOut)}</td><td>${money(m.lastIn - m.lastOut)}</td></tr>`;
    })
    .join('');

  const presentRows = machineIds
    .map((id) => {
      const m = run.machines[id];
      const net = m.netMachine;
      const cls = net >= 0 ? 'positive' : 'negative';
      return `<tr><td>${m.label}</td><td>${money(m.presentIn)}</td><td>${money(m.presentOut)}</td><td class="${cls}">${money(net)}</td></tr>`;
    })
    .join('');

  const submittedLine = run.submittedAt
    ? `<p>Submitted: ${formatFullDateTime(run.submittedAt)}</p>`
    : '<p>Status: NOT SUBMITTED</p>';

  const pct = run.storePercentage != null && run.vendorPercentage != null;

  const percentSection = pct
    ? `<h3>PERCENTAGE SPLIT</h3>
       <table>
         <tr><th>Store (${run.storePercentage}%)</th><td class="gold">${money(run.storeCalculatedAmount)}</td></tr>
         <tr><th>Vendor (${run.vendorPercentage}%)</th><td class="gold">${money(run.vendorCalculatedAmount)}</td></tr>
       </table>`
    : '';

  const photoRows = machineIds
    .filter((id) => !!run.machines[id].photoUrl)
    .map((id) => {
      const m = run.machines[id];
      return `<div class="photo-card"><p>${m.label}</p><img src="${m.photoUrl}" /></div>`;
    })
    .join('');

  const photoSection = photoRows
    ? `<h3>PHOTOS</h3><div class="photos">${photoRows}</div>`
    : '';

  return `
  <html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      body { font-family: 'Arial', sans-serif; background: #fff; color: #000; padding: 32px; }
      h1   { font-size: 22px; font-weight: 700; letter-spacing: 2px; border-bottom: 2px solid #C9A84C; padding-bottom: 8px; }
      h3   { font-size: 14px; color: #555; margin-top: 20px; margin-bottom: 6px; }
      table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 12px; }
      th   { background: #f5f5f5; padding: 8px; text-align: left; font-weight: 600; border-bottom: 1px solid #ddd; }
      td   { padding: 8px; border-bottom: 1px solid #eee; }
      .positive { color: #2ECC71; font-weight: 700; }
      .negative { color: #E74C3C; font-weight: 700; }
      .gold     { color: #C9A84C; font-weight: 700; }
      .hero     { font-size: 28px; font-weight: 700; text-align: right; }
      .photos   { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 8px; }
      .photo-card { width: 160px; border: 1px solid #eee; padding: 8px; }
      .photo-card p { margin: 0 0 6px 0; font-size: 11px; font-weight: 700; color: #555; }
      .photo-card img { width: 100%; height: 120px; object-fit: cover; }
      .footer   { margin-top: 32px; font-size: 10px; color: #999; }
    </style>
  </head>
  <body>
    <h1>${run.storeName}</h1>
    <p>Employee: ${run.employeeName} | Date: ${run.date} | Time: ${formatFullDateTime(run.timestamp)}</p>
    <p>Run ID: ${run.id}</p>

    <h3>LAST READING</h3>
    <table>
      <tr><th>Machine</th><th>Last IN</th><th>Last OUT</th><th>Net</th></tr>
      ${lastRows}
    </table>

    <h3>PRESENT READING</h3>
    <table>
      <tr><th>Machine</th><th>Present IN</th><th>Present OUT</th><th>Net (Delta)</th></tr>
      ${presentRows}
    </table>

    <h3>SUMMARY</h3>
    <table>
      <tr><th>Total New IN</th><td class="positive">${money(run.totalNewIn)}</td></tr>
      <tr><th>Total New OUT</th><td class="negative">${money(run.totalNewOut)}</td></tr>
      <tr><th>NET TOTAL</th><td class="hero ${run.isPositive ? 'positive' : 'negative'}">${money(run.netTotal)}</td></tr>
    </table>

    ${percentSection}
    ${photoSection}

    <p>Status: <strong class="${run.isPositive ? 'positive' : 'negative'}">${run.isPositive ? 'POSITIVE' : 'NEGATIVE'}</strong></p>
    ${submittedLine}

    <div class="footer">Generated by Machine Tracker App &middot; ${formatFullDateTime(Date.now())}</div>
  </body>
  </html>`;
}

export async function generateRunPdf(run: Run): Promise<void> {
  const html = buildHtml(run);

  if (Platform.OS === 'web') {
    // On web, open the print dialog directly.
    await Print.printAsync({ html });
    return;
  }

  const { uri } = await Print.printToFileAsync({ html });
  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `${run.storeName} Report` });
  } else {
    await Print.printAsync({ uri });
  }
}
